config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users do
    resources :websites 
    resource :settings
  end

  get 'home/index', as: 'home'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/update'

  get 'sessions/edit'

  get 'sessions/destroy'

  get 'sessions/index'

  get 'sessions/show'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/index'

  get 'users/show'

 get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy' 
  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
	belongs_to :user
	before_update :check_for_http

	def check_for_http
		if self.website1.match(/https?:\/\//) == nil
			self.website1 = "http://" + self.website1
		end

		if self.website2.match(/https?:\/\//) == nil
			self.website2 = "http://" + self.website2
		end

		if self.website3.match(/https?:\/\//) == nil
			self.website3 = "http://" + self.website3
		end

		if self.website4.match(/https?:\/\//) == nil
			self.website4 = "http://" + self.website4
		end		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_one :setting
	has_many :websites

	validates_presence_of :fname
	validates_presence_of :lname
	validates :email, uniqueness: { case_sensitive: true }
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates :password, length: { in: 4..20 }
	validates_presence_of :password 
	validates_confirmation_of :password
	

	after_create :set_defaults

    def set_defaults
		self.create_setting frames: 1, style: "1", skin: "white", background: "white", website1: "https://www.duckduckgo.com"
    end
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


	def index
		@user = User.new
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
#iets klopt hier niet
  def show
    @users = User.all
  end

  def new
  end

        def create
        user = User.find_by_email(params[:session][:email])
        # If the user exists AND the password entered is correct.
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          redirect_to user
        else
        # If user's login doesn't work, send them back to the login form.
          flash[:alert] = "Uh Oh! Something went wrong. Please reenter your credentials and try again."
          redirect_to home_path
        end
      end

      def destroy
        session.delete :user_id
        flash[:alert] = "Your secrets are safe. You have successfully logged out."
        redirect_to home_path

      end

   def update
   end

  def edit
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def new
  end

  def create
  end

  def update
    @user = User.find_by_id params[:user_id]
    @settings = @user.setting
    @settings.update setting_params
    redirect_to user_path @user
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def setting_params
      params.require(:setting).permit(:style, :skin, :frames, :background, :website1, :website2, :website3, :website4)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
   		@user = User.all
	end

  def new
   @user = User.new
  end

   def create
      @user = User.new user_params
      @settings = @user.setting
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "You have signed up for awesomeness:)"
        redirect_to home_path
      else
        flash[:alert] = "We were unable to sign you up. Please try again."
        redirect_to home_path
      end
    end

    def show
		@user = User.find_by_id params[:id]
		@settings = @user.setting
    if session[:user_id] != @user.id
      redirect_to home_path
      return
    end
		if @settings.frames == 1
			render :oneframe
		elsif @settings.frames == 2
			render :twoframe
		elsif @settings.frames == 3
			render :threeframe
		elsif @settings.frames == 4
			render :fourframe
		end 
	end 

	def update
	end

	def edit
	end

	def destroy
	end

	private
    def user_params
      params.require(:user).permit( :fname, :lname, :email, :password, :password_confirmation)
    end

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def user_link user
		link_text = if user == current_user
						'you'
					else
						"#{user.fname} #{user.lname}"
					end
		link_to link_text, user_path(user)
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end

end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/home/index.html.erb
<img src="/images/frames4.jpg" id="bg">
	<style type="text/css">
		#showmenu {
			display: none
		}</style>
<h1>
	Welcome to IFrameYou!
</h1>
<% if flash[:notice] or flash[:alert]%> 
<p id="flash">
<%= flash[:notice] if flash[:notice] %> 
<%= flash[:alert] if flash[:alert] %>
</p>
<% end %>

<table width="100%" align="left">
<p class="click"><a href = "javascript:void(0)" onclick = "createlightbox('signup-lightbox')">sign up </a>
</p>
<tr>
<td>
<div id="signup-lightbox" class="white_content" > 
<a href = "javascript:void(0)" onclick = "closelightbox('signup-lightbox')" style="float:right">
<img src="http://2.bp.blogspot.com/-aXHXnOQPBJM/Tx_p1qqNI4I/AAAAAAAAAeU/bH0tlsikADQ/s1600/icon_cancel.gif" alt="" /></a>      
<table align="center" cellpadding="5" cellspacing="5" >
<tr>
<td colspan="2" class="Title" align="center">Signup Form</td>
</tr>

<tr>
<td class="label">              
first Name:</td>
<td align="center">

<input id="Text1" type="text" /></td>
</tr>

<tr>
<td class="label">              
last Name:</td>
<td align="center">

<input id="Text1" type="text" /></td>
</tr>

<tr>
<td class="label">              
email:</td>
<td align="center">

<input id="Text1" type="text" /></td>
</tr>

<tr>
<td class="label">              
Password:</td>
<td align="center">

	<input id="Text2" type="password"/></td>
</tr>

<tr>
	<td class="label">              
		Confirm-Password:</td>
		<td align="center">
			<input id="Text3" type="password" /></td>
		</tr>

	<tr>
		<td>              
			<input id="Button1" type="button" value="sign-up"/>
		</td>
	</tr>
</table>
</div>
</td>
</tr>
</form>

<div id="refs">
	<p class="click leftclick"><a href = "javascript:void(0)" onclick = "createlightbox('signup-lightbox')"><img src="/images/signupbutton.jpg"></a></p>

	<p class="click rightclick"><a href = "javascript:void(0)" onclick = "createlightbox('login-lightbox')"><img src="/images/loginbutton.jpg"></a></p>
</div>

<table width="100%" align="left">
	<tr>
		<td>
		<div id="signup-lightbox" class="white_content" style="height:300px"> 
			<a href = "javascript:void(0)" onclick = "closelightbox('signup-lightbox')" style="float:right">
			<img src="/images/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5">
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Signup Form</span>
					</td>
				</tr>
  				<%= form_for @user, url: '/users' do |f| %>
				<tr>
					<td class="label">
						<%= f.label :fname, 'First Name' %>
					</td>
					<td align="center">
						<%= f.text_field :fname %>
					</td>
				</tr>
				<tr>
					<td class="label">            
						<%= f.label :lname, 'Last Name' %>
					</td>
					<td align="center">
						<%= f.text_field :lname %>
					</td>
				</tr>
				<tr>
					<td class="label">
						<%= f.label :email, 'Email' %>
					</td>
					<td align="center">
						<%= f.text_field :email %>
					</td>
				</tr>
				<tr>
					<td class="label">
						<%= f.label :password, 'Password' %>
					</td>
					<td align="center">
						<%= f.password_field :password %>
					</td>
				</tr>
				<tr>
					<td class="label">
						<%= f.label :password_confirmation, 'Password Confirmation' %>
					</td>
					<td align="center">
						<%= f.password_field :password_confirmation %>
					</td>
				</tr><br>
				<tr>
					<td colspan="2" class="title" align="center"><br>
	                     
                      <%= f.submit :'Sign Up!' %>

						
					</td>
				</tr>
				<% end %>
			</table>
		</div>
		</td>
	</tr>

</table>   

<div id="fade" class="black_overlay"></div>


<!-- login form -->

<table width="100%" align="left">
	<tr>
		<td>
		<div id="login-lightbox" class="white_content" > 
			<a href = "javascript:void(0)" onclick = "closelightbox('login-lightbox')" style="float:right">
			<img src="/images/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5" >
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Login Form</span>
					</td>
				</tr>
				<%= form_for(:session, url: '/login') do |f| %>
				<tr>
					<td class="label">              
						<%= f.label :email, 'Email' %>
					</td>
					<td align="center">
						<%= f.text_field :email %>
					</td>
				</tr>
				<tr>
					<td class="label">              
						<%= f.label :password, 'Password' %>
					</td>
					<td align="center">
						<%= f.password_field :password %>
					</td>
				</tr>
				<tr><br>
					<td colspan="2" class="title" align="center"><br>         
						<%= f.submit :'Login!' %>	
					</td>
				</tr>	
				<% end %>
			</table>
		</div>
		</td>

		</tr>
		</form>

	</tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iframeyou</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>



<div id="showmenu">
<% if current_user %>
	<% if current_user.setting.created_at == current_user.setting.updated_at %>
		<a href="#" class="menu tooltip <%= current_user.setting.background %>-bg <%= current_user.setting.skin %>"><img src="/images/threebars.png" id="image">
		    <span id="showtooltip">
		        <img class="callout" src="/images/callout_black.gif" />

		        <strong>Get Your Frame On!</strong><br />
		        Click the menu button to the right to get started. Click a selection under "Frames and Styles" to choose your view. Choose a "Skin" to determine the color of the frame border and chose a "Background" for your frames. Then just type in your websites and click submit!
		    </span>
		</a>
	<% else %>
		<a href="#" class="menu tooltip <%= current_user.setting.background %>-bg <%= current_user.setting.skin %>"><img src="/images/threebars.png" id="image">
		    <span id="fadetooltip">
		        <img class="callout" src="/images/callout_black.gif" />

		        <strong>Get Your Frame On!</strong><br />
		        Remember to click the menu button to the right to change your settings.
		    </span>
		</a>
	<% end %>

	<div class="settings <%= current_user.setting.background %>-bg <%= current_user.setting.skin %>">
		<a href="#" class="menubox"><img src="/images/threebars.png" id="image"></a>
		<br><br>
		<div class="category-box">
			<%= link_to "Log Out", logout_path, method: :delete, id: "menu-logout" %>
		</div>
		<div class="category-box">
			<p>
				Layout
			</p>
			<div id="frames-and-layout" class="parent">
				<a href="#" class="options" data-field-value="1" data-field-number="1"><img src="/images/1.png" class="icon1 one"></a>
				<a href="#" class="options" data-field-value="2h" data-field-number="2"><img src="/images/2h.png" class="icon1 two"></a>
				<a href="#" class="options" data-field-value="2v" data-field-number="2"><img src="/images/2v.png" class="icon1 two"></a>
				<a href="#" class="options" data-field-value="3h" data-field-number="3"><img src="/images/3h.png" class="icon1 three"></a>
				<a href="#" class="options" data-field-value="3t"  data-field-number="3"><img src="/images/3t.png" class="icon1 three"></a>
				<a href="#" class="options" data-field-value="3b"  data-field-number="3"><img src="/images/3b.png" class="icon1 three"></a>
				<a href="#" class="options" data-field-value="4a" data-field-number="4"><img src="/images/4a.png" class="icon1 four"></a>
				<a href="#" class="options" data-field-value="4t" data-field-number="4"><img src="/images/4t.png" class="icon1 four"></a>
				<a href="#" class="options" data-field-value="4b" data-field-number="4"><img src="/images/4b.png" class="icon1 four"></a>
			</div>
		</div>
		<div class="category-box">
			<p>
				Skin
			</p>
			<div id="skin" class="parent">
				<a href="#" class="options" data-field-value="black"><img src="/images/1.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="white"><img src="/images/whites.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="pink"><img src="/images/pinks.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="purple"><img src="/images/purples.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="blue"><img src="/images/blues.png" class="icon2"></a>
			</div>
		</div>
		<div class="category-box">
		<p>
			Background
		</p>
			<div id="background" class="parent">
				<a href="#" class="options" data-field-value="black"><img src="/images/black.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="white"><img src="/images/white.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="pink"><img src="/images/pink.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="purple"><img src="/images/purple.png" class="icon2"></a>
				<a href="#" class="options" data-field-value="blue"><img src="/images/blue.png" class="icon2"></a>
			</div>
		</div>
			<br><br>
		<%= form_for current_user.setting, url: user_settings_path(current_user) do |f| %>
		<%= f.hidden_field :frames %>
		<%= f.hidden_field :style %>
		<%= f.hidden_field :skin %>
		<%= f.hidden_field :background %>
		<div id="web1" class="categories category-box">
		<%= f.label :website1, 'Website For Frame One' %><br>
		<%= f.text_field :website1 %><br><br>
		</div>
		<div id="web2" class="categories category-box">
		<%= f.label :website2, 'Website For Frame Two' %><br>
		<%= f.text_field :website2 %><br><br>
		</div>
		<div id="web3" class="categories category-box">
		<%= f.label :website3, 'Website For Frame Three' %><br>
		<%= f.text_field :website3 %><br><br>
		</div>
		<div id="web4" class="categories category-box">
		<%= f.label :website4, 'Website For Frame Four' %><br>
		<%= f.text_field :website4 %><br><br>
		</div>
		<div id="submit">
			<%= f.submit 'Submit' %>
		</div>
		<% end %>
	</div>
<% end %>
</div>

<%= yield %>
<!--  -->
</body>
</html>

app/views/settings/create.html.erb
<h1>Settings#create</h1>
<p>Find me in app/views/settings/create.html.erb</p>

app/views/settings/destroy.html.erb
<h1>Settings#destroy</h1>
<p>Find me in app/views/settings/destroy.html.erb</p>

app/views/settings/edit.html.erb
<h1>Settings#edit</h1>
<p>Find me in app/views/settings/edit.html.erb</p>

app/views/settings/index.html.erb
<h1>Settings#index</h1>
<p>Find me in app/views/settings/index.html.erb</p>

app/views/settings/new.html.erb
<h1>Settings#new</h1>
<p>Find me in app/views/settings/new.html.erb</p>

app/views/settings/show.html.erb
<h1>Settings#show</h1>
<p>Find me in app/views/settings/show.html.erb</p>

app/views/settings/update.html.erb
<h1>Settings#update</h1>
<p>Find me in app/views/settings/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/fourframe.html.erb
<% if @settings.style == "4a" %>
	<iframe src="<%= @settings.website1 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe><br>
	<iframe src="<%= @settings.website3 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "4t" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="halfleftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="halfmiddlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="halfrightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "4b" %>
	<iframe src="<%= @settings.website3 %>" class="halfleftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="halfmiddlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website1 %>" class="halfrightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/oneframe.html.erb
	<iframe src="<%= @settings.website1 %>" class="<%= @settings.background %>-bg <%= @settings.skin %>" id="fullscreen"></iframe>

app/views/users/random.html.erb
	<iframe src="https://www.duckduckgo.com" id="topleft" style="border-color: " + <%= @settings.skin %>;></iframe>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/threeframe.html.erb
<% if @settings.style == "3h" %>
	<iframe src="<%= @settings.website3 %>" class="leftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="middlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website1 %>" class="rightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "3b" %>
	<iframe src="<%= @settings.website1 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "3t" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/twoframe.html.erb
<% if @settings.style == "2h" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "2v" %>
	<iframe src="<%= @settings.website1 %>" class="leftfull <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="rightfull <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/websites/create.html.erb
<h1>Websites#create</h1>
<p>Find me in app/views/websites/create.html.erb</p>

app/views/websites/destroy.html.erb
<h1>Websites#destroy</h1>
<p>Find me in app/views/websites/destroy.html.erb</p>

app/views/websites/edit.html.erb
<h1>Websites#edit</h1>
<p>Find me in app/views/websites/edit.html.erb</p>

app/views/websites/index.html.erb
<h1>Websites#index</h1>
<p>Find me in app/views/websites/index.html.erb</p>

app/views/websites/new.html.erb
<h1>Websites#new</h1>
<p>Find me in app/views/websites/new.html.erb</p>

app/views/websites/show.html.erb
<h1>Websites#show</h1>
<p>Find me in app/views/websites/show.html.erb</p>

app/views/websites/update.html.erb
<h1>Websites#update</h1>
<p>Find me in app/views/websites/update.html.erb</p>